### ISSUE TITLE
2 Player Turn Back to Frontend Progression

### ISSUE THREAD

**Issue by kaubster** [borisv13/kot#158]
response = from server to client
request = from client to server
^^^ =  Task Complete
Game Sequence: Startup, player given x turns, next player turn:

[**backend**] **Phase: Begin-Game**
^^^	receive "init_user_request"
^^^	once 2 players connect
^^^	initalize/start game
^^^send "begin_turn_response" _where_ payload = current_players_username

[**frontend**] **Phase: pre-roll-processing**
^^^receive "begin_turn_response"
^^^reset dice UI, console states "username, it your turn"
^^^	user selects "Roll"
^^^sends "roll_dice_request" _where_ payload = number_to_roll
	
[**backend**] **Phase: roll-dice**
^^^	receive "roll_dice_request"
^^^	sends "dice_rolls_response" _where_ payload = dice
	
[**frontend**] **Phase: post-roll processing**
^^^	receive "dice_rolls_response", updates dice board.
^^^	user selects dice to keep
^^^	user selects "Roll", sends "selected_dice_request" _where_ payload = 2d array of dice selected
	
[**backend**] **Phase: finish-rolling/resolve dice**
^^^	receive "selected_dice_request"
^^^updates game state
^^^check to see if player has remaining rolls
^^^if turn over
^^^  	GO TO **Phase:end-turn**
^^^else
^^^ 	GO TO **Phase:roll-dice** 

[**backend**] Phase:end-turn
^^^determine next_player_username
^^^send "begin_turn_response" payload = next_player_username

^^^Missing Message:
      command: "begin_turn_response",
      user: envelope.user,
      room: envelope.room,
      payload: username

**Comment by cvennel** [comment]
@kaubster do we need this?

**Comment by kaubster** [comment]
this was long since finished...
