### ISSUE TITLE
All buttons grayed out if AcceptDice before roll

### ISSUE THREAD

**Issue by cvennel** [borisv13/kot#233]
Clicking Roll before accept locks all dice

**Comment by kaubster** [comment]
Tried steps below to recreate this a few times... was unsuccessful at recreating.

Does anyone have steps to recreate?

Started game
clicked roll (saw dice change)
rolled again
accept (also used end turn prior to accept - dice resolved still)

**Comment by cvennel** [comment]
Start game, don't click roll, just click accept

**Comment by cvennel** [comment]
I think clicking accept dice if no dice are displayed is the problem

**Comment by kaubster** [comment]
yep, see it.
